name: project_manager_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  uuid: ^4.5.1
  logger: ^2.5.0
  http: ^1.2.2
  shared_preferences: ^2.3.4
  test: ^1.25.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  

flutter:
  
  uses-material-design: true
  
  assets:
      - assets/icon/manager.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700